### ISSUE TITLE
crash when encountering some CJK text amongst English

### ISSUE THREAD

**Issue by mark-summerfield** [ledongthuc/pdf#30]
I get a panic when trying to read the attached PDF file.
```
goroutine 1 [running]:
github.com/ledongthuc/pdf.(*buffer).errorf(...)
	/home/mark/opt/gows/pkg/mod/github.com/ledongthuc/pdf@v0.0.0-20220302134840-0c2507a12d80/lex.go:82
github.com/ledongthuc/pdf.(*buffer).readHexString(0xc0002a1720)
	/home/mark/opt/gows/pkg/mod/github.com/ledongthuc/pdf@v0.0.0-20220302134840-0c2507a12d80/lex.go:203 +0x2f6
github.com/ledongthuc/pdf.(*buffer).readToken(0xc0002a1720)
	/home/mark/opt/gows/pkg/mod/github.com/ledongthuc/pdf@v0.0.0-20220302134840-0c2507a12d80/lex.go:157 +0x165
github.com/ledongthuc/pdf.Interpret({0xc0001301e0?, {0x1138a0?, 0xc0?}, {0x4f8bc0?, 0xc000128120?}}, 0xc0002a18c0)
	/home/mark/opt/gows/pkg/mod/github.com/ledongthuc/pdf@v0.0.0-20220302134840-0c2507a12d80/ps.go:64 +0x145
github.com/ledongthuc/pdf.Page.Content({{0xc0001301e0?, {0x1?, 0x0?}, {0x4f1ec0?, 0xc000120a80?}}})
	/home/mark/opt/gows/pkg/mod/github.com/ledongthuc/pdf@v0.0.0-20220302134840-0c2507a12d80/page.go:816 +0x2b5
main.getChars(0x53cb78?, 0x1, 0x5126f3?)
	/home/mark/app/go/pdfdump/text.go:14 +0x85
main.outputWords(0xc0002a1f00, 0x40c41e?, 0x400000?, 0xc0000666b0?)
	/home/mark/app/go/pdfdump/output.go:75 +0x1ca
main.output(0xc000113f00)
	/home/mark/app/go/pdfdump/output.go:33 +0x1a5
main.main()
	/home/mark/app/go/pdfdump/pdfdump.go:12 +0x99
```
[99.pdf](https://github.com/ledongthuc/pdf/files/12067338/99.pdf)

**Comment by ledongthuc** [comment]
with latest source code, I got error:

```
panic: malformed hex string 4  b~|q<'8߻O~ES{o1}=7[zDcB]ǆ?҇z_}_.龗z_aZ^^^ n+W_z_k( {_
                  XDאtC,C`V`j
        EI Q
        q 96 0 0 -87 2132 5506 cm
        BI
        /IM true
        /W 96
        /H 87
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 96>>
cd      ID &|
         i~}ςKK//tK^>KKt~r`}    <#Ɂ?<@
        EI Q
        q 90 0 0 -75 2236 5513 cm
        BI
        /IM true
        /W 90
        /H 75
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 90>>
        ID &|`4H3\Z
                  a-]iu_ֿOu{ԜoKIi%U%
                                   m-acBpa
                                          =\=@i.arp.<H4d6r
        CYy
        EI Q
        q 87 0 0 -88 2337 5510 cm
        BI
        /IM true
        /W 87
        /H 88
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 87>>
        ID &GÑz
               /
,6      a[ummivml}o_Y[67'~߿~~}~f
                                p
        EI Q
        q 78 0 0 -78 2444 5517 cm
        BI
        /IM true
        /W 78
        /H 78
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 78>>
`       ID &S
c7/aua<0h0KaZkLZ69~m[k\5*v

        EI Q
        q 92 0 0 -82 2538 5522 cm
        BI
        /IM true
        /W 92
        /H 82
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 92>>
        ID &`3WL yvzhOCs
v?iuZ   #tZuik_[￷߿߶wo'~;oљ[pߠAۮiMxa/+^^
        EI Q
        q 68 0 0 -77 2647 5514 cm
        BI
        /IM true
        /W 68
        /H 77
        /BPC 1
        /D[1
        0]
        /F/CCF
        /DP<</K -1
        /Columns 68>>
-2.:!mmm{{{{{{{{0oD/h|Aj íil5il4
        EI Q
        Q
        q
        455 970 5040 6480 re W n
        /R8 cs
        0 0 0 scn
        q
        10 0 0 10 0 0 cm BT
        /R13 9 Tf
        1 0 0 1 271.9 544.45 Tm
        (")Tj
        /R11 10 Tf
        4.7 0.15 Td
        [(,)-347(held)-385(in)-384(the)-375(variable)]TJ
        /R13 9 Tf
        103.45 -0.15 Td
        (movie)Tj
        /R11 10 Tf
        23.5 0.15 Td
        [(.)-327(If)-505(we)-377.002(print)-382.002(the)]TJ
        -277.45 -12.25 Td
        [(string)-481(using)]TJ
        /R13 9 Tf
        62.7 -0.15 T

goroutine 1 [running]:
main.main()
        /Users/thucle/projects/ledongthuc/pdf/examples/read_plain_text/main.go:22 +0x135

```
will spent time later to check what problem

**Comment by kvii** [comment]
There has an inline image in your pdf. The key part:

```txt
q 95 0 0 -96 2029 5513 cm
BI
/IM true
/W 95
/H 96
/BPC 1
/D[1
0]
/F/CCF
/DP<</K -1
/Columns 95>>
ID (some binary data) % <--
EI Q
```

Code from `BI` to `EI` is the inline image, and data behind `ID` in binary data. Generally, a content stream only contains printable chars, so `readToken` does not handle this kind of stuff. I'll try to solve this problem.
